### PR TITLE
Update dependencies for Dart 2.0 stable.

### PR DESCRIPTION
**Pull request by jcollins-g**
Bring haikunator up to speed for Dart 2.0.

### CODE REVIEW

**Comment by Atrox** [comment]
Hey @jcollins-g, thanks for the PR. Oddly enough, I'm unable to publish the new library version. The last time I touched pub was 2015 (lately again for flutter though) and now it looks like I'm unable to authorize myself (Unauthorized user is not allowed to upload versions to package haikunator.), with my only google account. 

Do I remember wrong or didn't pub have a username/password system independent of google oauth back then? Could that be the issue?

I'll try to find someone I can contact about this, to get this fixed. If you know some place I can go to, that would help very much.

Thanks,
Atrox

**Comment by devoncarew** [comment]
To revive this issue, it looks like the email you'd uploaded the package with is '`mail@atrox.me`'.

We're using `package:haikunator` in DartPad; it would be great to have a 2.0 compatible version published - it would let us remove some technical debt in DartPad (we're relying on a forked version).

@kevmoo - is there any process for recovering a pub package (or adding a new uploader email for @Atrox)?

**Comment by Atrox** [comment]
Yeah, I tried to explain my issue in https://github.com/dart-lang/pub-dartlang-dart/issues/1460#issuecomment-411734541. Sadly mail@atrox.me was merged into my primary google account as a secondary email, which in result now prevents me from uploading the new version because pub only recognises primary email addresses on google accounts.

Sorry that I'm unable to publish the new version, this should be so easy to do...

**Comment by devoncarew** [comment]
Ah, I hadn't seen that comment on the other thread. It sounds like you don't want your primary email address listed on pub?

**Comment by Atrox** [comment]
Yeah exactly. I've got mail@atrox.me as secondary verified mail but pub sadly doesn't recognises that. I guess I have to let them transfer my package to my primary email but I don't like that because the email will be publicly listed and this is one of the mails I've kept spam free for a while now.

**Comment by kevmoo** [comment]
Is there anyway for your to prove you (still) own "mail@atrox.me" and the associated gmail address? If so, we can add a new uploader.

Could you email me @ kevmoo at google dot com?

**Comment by Atrox** [comment]
I sent you an email @kevmoo.

**Pull request merged**
